### ISSUE TITLE
If you have your own Gurobi already and enable it, the build procedure still downloads and compiles CLP

### ISSUE THREAD

**Issue by jeckstei** [aik7/Boosting#23]

**Comment by aik7** [comment]
I updated `scripts/build.sh`, so you can use the following commands.
```
sh sctipts/build.sh                   # compile Boosting with PEBBL, RMA, and CLP in the release mode
sh scripts/build.sh -d true          # compile Boosting with PEBBL, RMA, and CLP in the debug mode
sh scripts/build.sh -g true          # compile Boosting with PEBBL, RMA, CLP and Gurobi in the release mode
sh scripts/build.sh -d true -g true  # compile Boosting with PEBBL, RMA, CLP, and Gurobi in the debug mode
```



* CLP is no longer installed if it already exists in the `external` directory.
* Gurobi is no longer downloaded if it already exists in the `external` directory or you set `GUROBI_HOME` in the `.bashrc` file.
* The release or debug mode does not apply to CLP and Gurobi

* For the current implementation, you always have to have CLP, and Gurobi can be an optional.
